[phases.setup]
nixPkgs = ["...", "nodejs_20", "yarn"]

[phases.build]
cmds = [
  "mix deps.get --only prod",
  "cd assets && npm install --production",
  "cd assets && npm run build",
  "mix phx.digest",
  "mix compile",
  "mix release papercups"
]

[start]
cmd = "_build/prod/rel/papercups/bin/papercups eval \"ChatApi.Release.migrate()\" && _build/prod/rel/papercups/bin/papercups start"