[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
# healthcheckPath = "/"  # Temporarily disabled
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
startCommand = "/entrypoint.sh run"